# Generated by Django 6.0.5 on 2026-05-31 17:53

import django.db.models.deletion
import shortuuid.django_fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWeixinUser',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, db_index=True, editable=False, length=16, max_length=40, prefix='', verbose_name='UUID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新时间')),
                ('openid', models.CharField(db_index=True, max_length=128, verbose_name='OpenID')),
                ('unionid', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='UnionID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'historical 微信用户',
                'verbose_name_plural': 'historical 微信用户',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WeixinUser',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=16, max_length=40, prefix='', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('openid', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='OpenID')),
                ('unionid', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='UnionID')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weixin_user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '微信用户',
                'verbose_name_plural': '微信用户',
                'db_table': 'account_weixinuser',
            },
        ),
    ]
