# Generated by Django 6.0.5 on 2026-05-31 17:53

import django.db.models.deletion
import shortuuid.django_fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLog',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, db_index=True, editable=False, length=16, max_length=40, prefix='', verbose_name='UUID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新时间')),
                ('title', models.CharField(max_length=255, verbose_name='日志标题')),
                ('content', models.TextField(verbose_name='日志内容')),
                ('level', models.CharField(choices=[('INFO', '信息'), ('WARNING', '警告'), ('ERROR', '错误')], default='INFO', max_length=10, verbose_name='日志级别')),
                ('module', models.CharField(choices=[('order', '订单'), ('wechat_pay', '微信支付'), ('credit', '积分与会员')], db_index=True, max_length=20, verbose_name='模块')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 系统日志',
                'verbose_name_plural': 'historical 系统日志',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=16, max_length=40, prefix='', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=255, verbose_name='日志标题')),
                ('content', models.TextField(verbose_name='日志内容')),
                ('level', models.CharField(choices=[('INFO', '信息'), ('WARNING', '警告'), ('ERROR', '错误')], default='INFO', max_length=10, verbose_name='日志级别')),
                ('module', models.CharField(choices=[('order', '订单'), ('wechat_pay', '微信支付'), ('credit', '积分与会员')], db_index=True, max_length=20, verbose_name='模块')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'db_table': 'system_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='system_log_created_at_idx'), models.Index(fields=['module', 'created_at'], name='system_log_module_created_idx')],
            },
        ),
    ]
