# Generated by Django 5.2.14 on 2026-05-31 18:27

import django.db.models.deletion
import shortuuid.django_fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberTier',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=16, max_length=40, prefix='', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='等级名称')),
                ('price_per_month_minor', models.BigIntegerField(default=0, help_text='单位为分（1 元 = 100 分），免费为 0', verbose_name='月费（分）')),
                ('max_sessions', models.IntegerField(default=10, verbose_name='最大会话数')),
                ('max_workspaces', models.IntegerField(default=3, verbose_name='最大工作区数')),
                ('max_idle_minutes', models.IntegerField(default=30, help_text='超过此空闲时间将自动断开连接', verbose_name='最大空闲分钟数')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_default', models.BooleanField(default=False, help_text='新用户默认分配的等级', verbose_name='默认等级')),
            ],
            options={
                'verbose_name': '会员等级',
                'verbose_name_plural': '会员等级',
                'db_table': 'member_tier',
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalMemberTier',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, db_index=True, editable=False, length=16, max_length=40, prefix='', verbose_name='UUID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新时间')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='等级名称')),
                ('price_per_month_minor', models.BigIntegerField(default=0, help_text='单位为分（1 元 = 100 分），免费为 0', verbose_name='月费（分）')),
                ('max_sessions', models.IntegerField(default=10, verbose_name='最大会话数')),
                ('max_workspaces', models.IntegerField(default=3, verbose_name='最大工作区数')),
                ('max_idle_minutes', models.IntegerField(default=30, help_text='超过此空闲时间将自动断开连接', verbose_name='最大空闲分钟数')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_default', models.BooleanField(default=False, help_text='新用户默认分配的等级', verbose_name='默认等级')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 会员等级',
                'verbose_name_plural': 'historical 会员等级',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSubscription',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, db_index=True, editable=False, length=16, max_length=40, prefix='', verbose_name='UUID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新时间')),
                ('started_at', models.DateTimeField(db_index=True, verbose_name='开始时间')),
                ('expired_at', models.DateTimeField(db_index=True, verbose_name='到期时间')),
                ('paid_amount_minor', models.BigIntegerField(default=0, help_text='单位为分（1 元 = 100 分）', verbose_name='支付金额（分）')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('tier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='member.membertier', verbose_name='会员等级')),
            ],
            options={
                'verbose_name': 'historical 订阅记录',
                'verbose_name_plural': 'historical 订阅记录',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=16, max_length=40, prefix='', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('started_at', models.DateTimeField(db_index=True, verbose_name='开始时间')),
                ('expired_at', models.DateTimeField(db_index=True, verbose_name='到期时间')),
                ('paid_amount_minor', models.BigIntegerField(default=0, help_text='单位为分（1 元 = 100 分）', verbose_name='支付金额（分）')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='member.membertier', verbose_name='会员等级')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订阅记录',
                'verbose_name_plural': '订阅记录',
                'db_table': 'member_subscription',
                'ordering': ('-created_at',),
            },
        ),
    ]
