# Generated by Django 6.0.5 on 2026-05-31 17:53

import django.db.models.deletion
import shortuuid.django_fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWechatOrder',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, db_index=True, editable=False, length=16, max_length=40, prefix='', verbose_name='UUID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新时间')),
                ('prepay_id', models.CharField(blank=True, default='', max_length=128, verbose_name='预支付ID')),
                ('prepay_id_expires', models.DateTimeField(blank=True, default=None, null=True, verbose_name='预支付ID过期时间')),
                ('native_code_url', models.TextField(blank=True, default='', verbose_name='Native code_url')),
                ('native_code_url_expires', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Native code_url 过期时间')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': 'historical 微信支付订单',
                'verbose_name_plural': 'historical 微信支付订单',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWechatPayRefund',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, db_index=True, editable=False, length=16, max_length=40, prefix='', verbose_name='UUID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新时间')),
                ('wx_refund_id', models.CharField(db_index=True, max_length=64, verbose_name='微信支付退款单号')),
                ('raw_data', models.TextField(blank=True, default='', verbose_name='原始数据')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('refund', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.refund', verbose_name='关联退款单')),
            ],
            options={
                'verbose_name': 'historical 微信退款记录',
                'verbose_name_plural': 'historical 微信退款记录',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWechatPayTransaction',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, db_index=True, editable=False, length=16, max_length=40, prefix='', verbose_name='UUID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新时间')),
                ('transaction_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='微信支付订单号')),
                ('out_trade_no', models.CharField(db_index=True, max_length=64, verbose_name='微信支付商户订单号')),
                ('total_minor', models.BigIntegerField(default=0, verbose_name='总金额(分)')),
                ('payer_total_minor', models.BigIntegerField(default=0, verbose_name='用户支付金额(分)')),
                ('trade_state', models.CharField(choices=[('SUCCESS', '支付成功'), ('REFUND', '转入退款'), ('NOTPAY', '未支付'), ('CLOSED', '已关闭')], default='NOTPAY', max_length=20, verbose_name='交易状态')),
                ('trade_state_desc', models.CharField(blank=True, default='', max_length=256, verbose_name='交易状态描述')),
                ('success_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='支付完成时间')),
                ('raw_data', models.TextField(blank=True, default='', verbose_name='原始数据')),
                ('source', models.CharField(choices=[('api', 'API查询'), ('notify', '支付通知')], max_length=10, verbose_name='交易单来源')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.order', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': 'historical 微信支付单',
                'verbose_name_plural': 'historical 微信支付单',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WechatOrder',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=16, max_length=40, prefix='', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('prepay_id', models.CharField(blank=True, default='', max_length=128, verbose_name='预支付ID')),
                ('prepay_id_expires', models.DateTimeField(blank=True, default=None, null=True, verbose_name='预支付ID过期时间')),
                ('native_code_url', models.TextField(blank=True, default='', verbose_name='Native code_url')),
                ('native_code_url_expires', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Native code_url 过期时间')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_obj', to='order.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '微信支付订单',
                'verbose_name_plural': '微信支付订单',
                'db_table': 'wechat_order',
            },
        ),
        migrations.CreateModel(
            name='WechatPayRefund',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=16, max_length=40, prefix='', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('wx_refund_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='微信支付退款单号')),
                ('raw_data', models.TextField(blank=True, default='', verbose_name='原始数据')),
                ('refund', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wxpay_refunds', to='order.refund', verbose_name='关联退款单')),
            ],
            options={
                'verbose_name': '微信退款记录',
                'verbose_name_plural': '微信退款记录',
                'db_table': 'wechat_pay_refund',
            },
        ),
        migrations.CreateModel(
            name='WechatPayTransaction',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=16, max_length=40, prefix='', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('transaction_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='微信支付订单号')),
                ('out_trade_no', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='微信支付商户订单号')),
                ('total_minor', models.BigIntegerField(default=0, verbose_name='总金额(分)')),
                ('payer_total_minor', models.BigIntegerField(default=0, verbose_name='用户支付金额(分)')),
                ('trade_state', models.CharField(choices=[('SUCCESS', '支付成功'), ('REFUND', '转入退款'), ('NOTPAY', '未支付'), ('CLOSED', '已关闭')], default='NOTPAY', max_length=20, verbose_name='交易状态')),
                ('trade_state_desc', models.CharField(blank=True, default='', max_length=256, verbose_name='交易状态描述')),
                ('success_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='支付完成时间')),
                ('raw_data', models.TextField(blank=True, default='', verbose_name='原始数据')),
                ('source', models.CharField(choices=[('api', 'API查询'), ('notify', '支付通知')], max_length=10, verbose_name='交易单来源')),
                ('order', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wxpay_transactions', to='order.order', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '微信支付单',
                'verbose_name_plural': '微信支付单',
                'db_table': 'wechat_pay_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
