# Generated by Django 6.0.5 on 2026-05-31 17:53

import django.db.models.deletion
import shortuuid.django_fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrderItem',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, db_index=True, editable=False, length=16, max_length=40, prefix='', verbose_name='UUID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新时间')),
                ('kind', models.CharField(choices=[('generic', '通用')], default='generic', max_length=64, verbose_name='品类')),
                ('params', models.JSONField(default=dict, verbose_name='参数')),
                ('normalized_key', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='规范化键')),
                ('amount_minor', models.BigIntegerField(verbose_name='应付金额(分)')),
                ('original_amount_minor', models.BigIntegerField(default=0, verbose_name='原价(分)')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='货币')),
                ('execute_status', models.IntegerField(choices=[(10, '待履约'), (30, '已履约')], db_index=True, default=10, verbose_name='履约状态')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('buyer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='买家')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 订单项',
                'verbose_name_plural': 'historical 订单项',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=16, max_length=40, prefix='', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.IntegerField(choices=[(10, '待支付'), (30, '已支付'), (90, '已关闭')], db_index=True, default=10, verbose_name='订单状态')),
                ('payment_platform', models.CharField(choices=[('wechatpay_jsapi', '微信支付(JSAPI)'), ('wechatpay_native', '微信支付(Native)'), ('wechatpay_xpay', '微信支付(XPay)'), ('alipay', '支付宝')], default='wechatpay_native', max_length=32, verbose_name='支付平台')),
                ('amount_minor', models.BigIntegerField(verbose_name='应付金额(分)')),
                ('original_amount_minor', models.BigIntegerField(default=0, verbose_name='原价(分)')),
                ('paid_amount_minor', models.BigIntegerField(default=0, verbose_name='实收金额(分)')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='货币')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_orders', to=settings.AUTH_USER_MODEL, verbose_name='买家')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order_order',
            },
        ),
        migrations.CreateModel(
            name='HistoricalRefund',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, db_index=True, editable=False, length=16, max_length=40, prefix='', verbose_name='UUID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新时间')),
                ('refund_amount_minor', models.BigIntegerField(default=0, verbose_name='退款金额(分)')),
                ('status', models.CharField(choices=[('draft', '草稿')], default='draft', max_length=16, verbose_name='退款状态')),
                ('reason', models.TextField(blank=True, default='', verbose_name='退款原因')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': 'historical 退款',
                'verbose_name_plural': 'historical 退款',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=16, max_length=40, prefix='', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('kind', models.CharField(choices=[('generic', '通用')], default='generic', max_length=64, verbose_name='品类')),
                ('params', models.JSONField(default=dict, verbose_name='参数')),
                ('normalized_key', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='规范化键')),
                ('amount_minor', models.BigIntegerField(verbose_name='应付金额(分)')),
                ('original_amount_minor', models.BigIntegerField(default=0, verbose_name='原价(分)')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='货币')),
                ('execute_status', models.IntegerField(choices=[(10, '待履约'), (30, '已履约')], db_index=True, default=10, verbose_name='履约状态')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_order_items', to=settings.AUTH_USER_MODEL, verbose_name='买家')),
            ],
            options={
                'verbose_name': '订单项',
                'verbose_name_plural': '订单项',
                'db_table': 'order_orderitem',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='order.orderitem', verbose_name='订单项'),
        ),
        migrations.CreateModel(
            name='HistoricalOrder',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, db_index=True, editable=False, length=16, max_length=40, prefix='', verbose_name='UUID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新时间')),
                ('status', models.IntegerField(choices=[(10, '待支付'), (30, '已支付'), (90, '已关闭')], db_index=True, default=10, verbose_name='订单状态')),
                ('payment_platform', models.CharField(choices=[('wechatpay_jsapi', '微信支付(JSAPI)'), ('wechatpay_native', '微信支付(Native)'), ('wechatpay_xpay', '微信支付(XPay)'), ('alipay', '支付宝')], default='wechatpay_native', max_length=32, verbose_name='支付平台')),
                ('amount_minor', models.BigIntegerField(verbose_name='应付金额(分)')),
                ('original_amount_minor', models.BigIntegerField(default=0, verbose_name='原价(分)')),
                ('paid_amount_minor', models.BigIntegerField(default=0, verbose_name='实收金额(分)')),
                ('currency', models.CharField(default='CNY', max_length=3, verbose_name='货币')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('buyer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='买家')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.orderitem', verbose_name='订单项')),
            ],
            options={
                'verbose_name': 'historical 订单',
                'verbose_name_plural': 'historical 订单',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=16, max_length=40, prefix='', primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('refund_amount_minor', models.BigIntegerField(default=0, verbose_name='退款金额(分)')),
                ('status', models.CharField(choices=[('draft', '草稿')], default='draft', max_length=16, verbose_name='退款状态')),
                ('reason', models.TextField(blank=True, default='', verbose_name='退款原因')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='order.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '退款',
                'verbose_name_plural': '退款',
                'db_table': 'order_refund',
            },
        ),
    ]
